######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += \
  net_socket.hh \
  chat_dialog.hh \
  message.hh

SOURCES += \
  chat_dialog.cpp \
  net_socket.cpp \
  message.cpp \
  main.cc
